version: 2

jobs:
  build_and_test:
    machine: true
    working_directory: ~/CircleCI/docker-airflow
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      -run:
          name: Build
          command: |
            make build
      - run: 
          name: Test
          command: |
            make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
